/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hattmakarna;
import oru.inf.InfDB; 
import oru.inf.InfException; 
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.time.*;
import java.util.Locale;

/**
 *
 * @author mejaa
 */
public class KalenderSchemaRatt extends javax.swing.JPanel {
    private InfDB idb; 
    private String inloggadAnvandare; 
    private JPanel kalenderRuta;
    private JLabel manadLabel;
    private LocalDate visadManad;

    /**
     * Creates new form KalenderSchemaRatt
     */
    public KalenderSchemaRatt(InfDB idb, String ePost) {
        initComponents();
        this.idb = idb; 
        this.inloggadAnvandare = ePost;
        
        this.setLayout(new BorderLayout());
        visadManad = LocalDate.now().withDayOfMonth(1);
        
        JPanel toppPanel = new JPanel(new BorderLayout());
        JButton forraKnapp = new JButton("<");
        JButton nastaKnapp = new JButton(">");
        
        manadLabel = new JLabel("", SwingConstants.CENTER);
        toppPanel.add(forraKnapp, BorderLayout.WEST);
        toppPanel.add(manadLabel, BorderLayout.CENTER);
        toppPanel.add(nastaKnapp, BorderLayout.EAST);
        
        this.add(toppPanel, BorderLayout.NORTH);
        
        kalenderRuta = new JPanel();
        kalenderRuta.setLayout(new GridLayout(0, 7));
        this.add(kalenderRuta, BorderLayout.CENTER);
        
        forraKnapp.addActionListener(e -> {
            visadManad = visadManad.minusMonths(1);
            fyllKalender();
        });
        
        nastaKnapp.addActionListener(e -> {
            visadManad = visadManad.plusMonths(1);
            fyllKalender();
        });
        
        fyllKalender();
    }
    
    private void fyllKalender(){
        kalenderRuta.removeAll();
        
        String manadText = visadManad.getMonth().getDisplayName(TextStyle.FULL, new Locale("sv")) + " " + visadManad.getYear();
        manadLabel.setText(manadText.substring(0, 1).toUpperCase() + manadText.substring(1));
        
        String[] dagar = {"Mån", "Tis", "Ons", "Tor", "Fre", "Lör", "Sön"};
        for(String dag:dagar){
            JLabel lbl = new JLabel(dag, SwingConstants.CENTER);
            lbl.setFont(lbl.getFont().deriveFont(Font.BOLD));
            kalenderRuta.add(lbl);
        }
        
        LocalDate start = visadManad;
        int forstaDag = start.getDayOfWeek().getValue();
        int dagarIManad = visadManad.lengthOfMonth();
        
        for(int i = 1; i < forstaDag; i++){
            kalenderRuta.add(new JLabel(""));
        }
        
        for(int dag = 1; dag <= dagarIManad; dag++){
            JButton dagKnapp = new JButton(String.valueOf(dag));
            kalenderRuta.add(dagKnapp);
        }
        
        kalenderRuta.revalidate();
        kalenderRuta.repaint();
    }
    
    public static void main(String[] args){
        SwingUtilities.invokeLater(() -> {
            JFrame fonster = new JFrame("Min Kalender");
            fonster.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            fonster.setSize(600, 400);
            fonster.setContentPane(new KalenderSchemaRatt(idb, ePost));
            fonster.setVisible(true);
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
