/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;

import java.util.HashMap;
import java.util.List;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author oscar
 */
public class LaggTillProdukt extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;

    /*
     * Creates new form LaggTillProdukt
     */
    public LaggTillProdukt(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        artikelNummer = new javax.swing.JLabel();
        namn = new javax.swing.JLabel();
        pris = new javax.swing.JLabel();
        huvudmatt = new javax.swing.JLabel();
        txtArtikelnummer = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        txtPris = new javax.swing.JTextField();
        txtHuvudmatt = new javax.swing.JTextField();
        btnLaggTill = new javax.swing.JButton();
        modell = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        txtModell = new javax.swing.JTextField();
        txtText = new javax.swing.JTextField();
        tillbakaknapp = new javax.swing.JButton();
        laggTillMaterial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        artikelNummer.setText("Artikelnummer");

        namn.setText("Namn");

        pris.setText("Pris");

        huvudmatt.setText("Huvudmått");

        txtArtikelnummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtikelnummerActionPerformed(evt);
            }
        });

        txtNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamnActionPerformed(evt);
            }
        });

        txtPris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrisActionPerformed(evt);
            }
        });

        btnLaggTill.setText("Lägg till");
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });

        modell.setText("Modell");

        text.setText("Text");

        tillbakaknapp.setText("Tillbaka");
        tillbakaknapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tillbakaknappActionPerformed(evt);
            }
        });

        laggTillMaterial.setText("Lägg till material");
        laggTillMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laggTillMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtModell, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtHuvudmatt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtPris, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(artikelNummer)
                                    .addComponent(namn))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtArtikelnummer, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(txtNamn))))))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(laggTillMaterial)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLaggTill)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(huvudmatt)
                                .addComponent(pris)
                                .addComponent(modell)
                                .addComponent(text)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                                .addComponent(tillbakaknapp)
                                .addGap(75, 75, 75)))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artikelNummer)
                    .addComponent(txtArtikelnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namn)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pris)
                    .addComponent(txtPris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huvudmatt)
                    .addComponent(txtHuvudmatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modell)
                    .addComponent(txtModell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text)
                    .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(laggTillMaterial)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLaggTill)
                    .addComponent(tillbakaknapp))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamnActionPerformed

    private void txtArtikelnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtikelnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtikelnummerActionPerformed

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        // TODO add your handling code here:
        String textartikelNummer = txtArtikelnummer.getText();
        String namn = txtNamn.getText();
        String textPris = txtPris.getText();
        String textHuvudmatt = txtHuvudmatt.getText();
        String modell = txtModell.getText();
        String text = txtText.getText();

        try {
            int pris = Integer.parseInt(textPris);
            int huvudmatt = Integer.parseInt(textHuvudmatt);
            int artikelNummer = Integer.parseInt(textartikelNummer);
            if (Validering.faltInteTomt(textartikelNummer)
                    && Validering.faltInteTomt(namn)
                    && Validering.faltInteTomt(textPris)
                    && Validering.faltInteTomt(textHuvudmatt)
                    && Validering.faltInteTomt(modell)
                    && Validering.faltInteTomt(text)) {
                try {
                    String hamtaID = "Select max(StandardProduktID) from StandardProdukt;";
                    String nyHamtaID = idb.fetchSingle(hamtaID);
                    int nyID = Integer.parseInt(nyHamtaID) + 1;

                    String fragaLaggTill = "INSERT INTO StandardProdukt (StandardProduktID, Namn, Modell, Text, Storlek, Pris, Artikelnummer) "
                            + "VALUES (" + nyID + ", '" + namn + "', '" + modell + "', '" + text + "', "
                            + huvudmatt + ", " + pris + ", " + artikelNummer + ");";

                    idb.insert(fragaLaggTill);
                    JOptionPane.showMessageDialog(null, "Produkt är tillagd!");

                } catch (InfException e) {
                    JOptionPane.showMessageDialog(null, "Misslyckade att spara" + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Fälten får inte vara tomma!");
            }
        } catch (NumberFormatException numb) {
            JOptionPane.showMessageDialog(null, "Pris, huvudmått och artikelnummer måste innehålla endast siffror!");
        }

    }//GEN-LAST:event_btnLaggTillActionPerformed

    private void txtPrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrisActionPerformed

    private void tillbakaknappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tillbakaknappActionPerformed
        // TODO add your handling code here:
        new SeAllaProdukter(idb, inloggadAnvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tillbakaknappActionPerformed

    private void laggTillMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laggTillMaterialActionPerformed
        // TODO add your handling code here:
        new LaggTillMaterial(idb, inloggadAnvandare, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_laggTillMaterialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artikelNummer;
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JLabel huvudmatt;
    private javax.swing.JButton laggTillMaterial;
    private javax.swing.JLabel modell;
    private javax.swing.JLabel namn;
    private javax.swing.JLabel pris;
    private javax.swing.JLabel text;
    private javax.swing.JButton tillbakaknapp;
    private javax.swing.JTextField txtArtikelnummer;
    private javax.swing.JTextField txtHuvudmatt;
    private javax.swing.JTextField txtModell;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtPris;
    private javax.swing.JTextField txtText;
    // End of variables declaration//GEN-END:variables
}
