/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;

import oru.inf.InfDB; 
import oru.inf.InfException; 
import javax.swing.JOptionPane;
import java.awt.*;
/**
 *
 * @author helinakravi
 */
public class LäggTillNyKund extends javax.swing.JFrame {
 
    private static InfDB idb; 
    private String inloggadAnvandare;
    private Validering validera;



public LäggTillNyKund(InfDB idb, String inloggadAnvandare) {
    
    initComponents();
    this.idb = idb;
    this.inloggadAnvandare = inloggadAnvandare;
    }

    

//skyddar mot sql-injektion, genom att byta ut ' mot två'' (så att databasen inte tror att man avslutar koden tex)
private void sparaKund() {
    String telefonNummer = txtTelefonNr.getText();
    String fakturaAdress = txtFakturaAdress.getText(); 
    String leveransAdress = TxtLeveransAdress.getText();
    String leveransPostnummer = txtLeveransPostnummer.getText();
    String leveransOrt = txtLeveransOrt.getText();
    String leveransLand = txtLeveransLand.getText();
    String fakturaPostnummer = txtFakturaPostnummer.getText();
    String fakturaOrt = txtFakturaOrt.getText();
    String fakturaLand = txtLeveransLand.getText();
    String förnamn = txtFornamn.getText();
    String efternamn = TxtEfternamn.getText();
    String epost = TxtEpost.getText();

    // Kontrollera att inga fält är tomma
    if (!Validering.faltInteTomt(förnamn) || !Validering.faltInteTomt(efternamn) ||
        !Validering.faltInteTomt(epost) || !Validering.faltInteTomt(telefonNummer) ||
        !Validering.faltInteTomt(fakturaAdress) || !Validering.faltInteTomt(fakturaPostnummer) ||
        !Validering.faltInteTomt(fakturaOrt) || !Validering.faltInteTomt(fakturaLand) ||
        !Validering.faltInteTomt(leveransAdress) || !Validering.faltInteTomt(leveransPostnummer) ||
        !Validering.faltInteTomt(leveransOrt) || !Validering.faltInteTomt(leveransLand)) {
        
        JOptionPane.showMessageDialog(this, "Alla fält måste fyllas i!", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validera namn
    if (!Validering.arEndastBokstaver(förnamn)) {
        JOptionPane.showMessageDialog(this, "Förnamn får endast innehålla bokstäver", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Validering.arEndastBokstaver(efternamn)) {
        JOptionPane.showMessageDialog(this, "Efternamn får endast innehålla bokstäver", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validera e-post
    if (!Validering.valideringEmail(epost)) {
        JOptionPane.showMessageDialog(this, "Ogiltig e-postadress", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validera telefonnummer
    if (!Validering.valideringTelefon(telefonNummer)) {
        JOptionPane.showMessageDialog(this, "Telefonnummer måste ha formatet XXX-XXX-XXXX och enbart siffror", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validera postnummer
    if (!Validering.arEndastSiffror(leveransPostnummer) || !Validering.arEndastSiffror(fakturaPostnummer)) {
        JOptionPane.showMessageDialog(this, "Postnummer får endast innehålla siffror", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        String fraga = "INSERT INTO Kund (Fornamn, Efternamn, Epost, Telefonnummer, LeveransAdress, LeveransPostnummer, LeveransOrt, LeveransLand, " +
                       "FakturaAdress, FakturaPostnummer, FakturaOrt, FakturaLand) " +
                       "VALUES ('" + förnamn + "', '" + efternamn + "', '" + epost + "', '" + telefonNummer + "', '" + 
                       leveransAdress + "', '" + leveransPostnummer + "', '" + leveransOrt + "', '" + leveransLand + "', '" + 
                       fakturaAdress + "', '" + fakturaPostnummer + "', '" + fakturaOrt + "', '" + fakturaLand + "')";

        idb.insert(fraga);
        JOptionPane.showMessageDialog(this, "Kunddata har sparats!");
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Fel vid sparning till databas: " + ex.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);  
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblFörnamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTelefonnr = new javax.swing.JLabel();
        lblLeveransOrt = new javax.swing.JLabel();
        lblLeveransAdress = new javax.swing.JLabel();
        lblLeveransPostNr = new javax.swing.JLabel();
        txtFornamn = new javax.swing.JTextField();
        txtTelefonNr = new javax.swing.JTextField();
        TxtEpost = new javax.swing.JTextField();
        TxtLeveransAdress = new javax.swing.JTextField();
        txtLeveransPostnummer = new javax.swing.JTextField();
        txtLeveransOrt = new javax.swing.JTextField();
        TxtEfternamn = new javax.swing.JTextField();
        btnTillbaka = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        lblFakturaAdress = new javax.swing.JLabel();
        txtFakturaAdress = new javax.swing.JTextField();
        lblFakturaPostNr = new javax.swing.JLabel();
        txtFakturaPostnummer = new javax.swing.JTextField();
        txtFakturaOrt = new javax.swing.JTextField();
        lblFakturaOrt = new javax.swing.JLabel();
        txtLeveransLand = new javax.swing.JTextField();
        txtFakturaLand = new javax.swing.JTextField();
        lblLeveransLand = new javax.swing.JLabel();
        lblFakturaLand = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField7.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Lägg till ny kund ");
        jLabel1.setSize(new java.awt.Dimension(60, 25));

        lblFörnamn.setText("Förnamn");

        lblEfternamn.setText("Efternamn");

        lblEpost.setText("Epost");

        lblTelefonnr.setText("Telefonnummer");

        lblLeveransOrt.setText("Ort");

        lblLeveransAdress.setText("Leveransadress");

        lblLeveransPostNr.setText("Postnummer");

        txtFornamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornamnActionPerformed(evt);
            }
        });

        txtTelefonNr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonNrActionPerformed(evt);
            }
        });

        TxtLeveransAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLeveransAdressActionPerformed(evt);
            }
        });

        txtLeveransPostnummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeveransPostnummerActionPerformed(evt);
            }
        });

        txtLeveransOrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeveransOrtActionPerformed(evt);
            }
        });

        TxtEfternamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEfternamnActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        lblFakturaAdress.setText("Fakturaadress");

        lblFakturaPostNr.setText("Postnummer");

        lblFakturaOrt.setText("Ort");

        lblLeveransLand.setText("Land");

        lblFakturaLand.setText("Land");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefonnr)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFörnamn)
                            .addComponent(lblEpost)
                            .addComponent(lblEfternamn)
                            .addComponent(jLabel1)
                            .addComponent(lblLeveransAdress)
                            .addComponent(lblFakturaAdress))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtEpost)
                    .addComponent(txtTelefonNr)
                    .addComponent(TxtEfternamn)
                    .addComponent(txtFornamn)
                    .addComponent(TxtLeveransAdress, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txtFakturaAdress))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeveransPostNr)
                    .addComponent(lblFakturaPostNr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFakturaPostnummer)
                    .addComponent(txtLeveransPostnummer))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLeveransOrt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLeveransOrt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFakturaOrt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFakturaOrt)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLeveransLand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLeveransLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFakturaLand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFakturaLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 89, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTillbaka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSpara)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFörnamn))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEfternamn))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEpost)
                        .addComponent(TxtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonnr))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtLeveransAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeveransAdress)
                    .addComponent(lblLeveransPostNr)
                    .addComponent(txtLeveransPostnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLeveransOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeveransOrt)
                    .addComponent(txtLeveransLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeveransLand))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFakturaAdress)
                    .addComponent(txtFakturaAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFakturaPostNr)
                    .addComponent(txtFakturaPostnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFakturaOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFakturaOrt)
                    .addComponent(txtFakturaLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFakturaLand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnSpara))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtEfternamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEfternamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEfternamnActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
    sparaKund();
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
    new AllaKunder(idb, inloggadAnvandare).setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void txtTelefonNrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonNrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonNrActionPerformed

    private void txtFornamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornamnActionPerformed

    private void TxtLeveransAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLeveransAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLeveransAdressActionPerformed

    private void txtLeveransPostnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeveransPostnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeveransPostnummerActionPerformed

    private void txtLeveransOrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeveransOrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeveransOrtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LäggTillNyKund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LäggTillNyKund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LäggTillNyKund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LäggTillNyKund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LäggTillNyKund().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtEfternamn;
    private javax.swing.JTextField TxtEpost;
    private javax.swing.JTextField TxtLeveransAdress;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFakturaAdress;
    private javax.swing.JLabel lblFakturaLand;
    private javax.swing.JLabel lblFakturaOrt;
    private javax.swing.JLabel lblFakturaPostNr;
    private javax.swing.JLabel lblFörnamn;
    private javax.swing.JLabel lblLeveransAdress;
    private javax.swing.JLabel lblLeveransLand;
    private javax.swing.JLabel lblLeveransOrt;
    private javax.swing.JLabel lblLeveransPostNr;
    private javax.swing.JLabel lblTelefonnr;
    private javax.swing.JTextField txtFakturaAdress;
    private javax.swing.JTextField txtFakturaLand;
    private javax.swing.JTextField txtFakturaOrt;
    private javax.swing.JTextField txtFakturaPostnummer;
    private javax.swing.JTextField txtFornamn;
    private javax.swing.JTextField txtLeveransLand;
    private javax.swing.JTextField txtLeveransOrt;
    private javax.swing.JTextField txtLeveransPostnummer;
    private javax.swing.JTextField txtTelefonNr;
    // End of variables declaration//GEN-END:variables
}
    
