/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;

import java.awt.*;
import java.awt.event.*;
import java.net.URL;
import javax.swing.*;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author linodeluca
 */
public class MainFrame extends javax.swing.JFrame {
    private static InfDB idb;
    
    //Skapar fält för varje panel som ska visas i menyn
    private KalenderSchemaRatt kalenderPanel;
    private SeAllaOrdrar allaOrdrarPanel;
    private SeAllaKunder allaKunderPanel;
    private SeAllaLagerfordaProdukter allaLagerfordaProdukterPanel;
    private SkapaNyOrder nyOrderPanel;
    private SkapaNySpecialOrder skapaSpecialOrderPanel;
    private SeForsaljningsstatistik seForsaljningsstatistikPanel;
    private HanteraAllaAnstallda hanteraAllaAnstalldaPanel;
    private SkapaNyFraktsedel fraktsedelPanel;
    //Fält för att anropa validerings klassen
    private Validering validera;
    //private MainFrame parentFrame;  // referens till MainFrame


    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame(InfDB idb) {
    initComponents();
    // Se till att layouten på MainFrame är BorderLayout
    this.setLayout(new BorderLayout());

    // Lägg till jPanel1 i mitten
    this.add(jPanel1, BorderLayout.CENTER);

    // Lägg padding runt om
    jPanel1.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
    jPanel1.setLayout(new CardLayout()); // säkerställ att den verkligen har rätt layout
    this.idb = idb;
    lblFelMeddelande.setVisible(false);
    txtfEmail.setText("karin@hattmakarna.se");
    pswfLosenord.setText("hatt123");
    lblFelMeddelande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    // Vi vill inte att menyn ska visas förens vi loggat in
    jMenuBar1.setVisible(false);

    // Anpassa menyn (eventuella justeringar för menyer)
    for (int i = 0; i < jMenuBar1.getMenuCount(); i++) {
        JMenu menu = jMenuBar1.getMenu(i);
        menu.setOpaque(true);
        menu.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createEmptyBorder(5, 10, 5, 10), // spacing
            BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)
        ));
    }
    
    // Ladda bilden från src/hattmakarna/hattmakarna_logotyp.png
    URL imageURL = getClass().getResource("/hattmakarna/hattmakarna_logotyp.png");

    // Kontrollera om bilden finns
    if (imageURL != null) {
        // Skapa en ImageIcon med den laddade bilden
        ImageIcon icon = new ImageIcon(imageURL);

        // Skala om bilden till t.ex. 200x200 pixlar
        Image scaledImage = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);

        // Lägg in den skalade bilden i JLabel
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        logotyp.setIcon(scaledIcon);
    } else {
        // Om bilden inte hittades, skriv ut ett felmeddelande
        System.out.println("Bilden kunde inte hittas. Kontrollera sökvägen.");
    }
}

        private void loggaUt() {
        //När man trycker på logga ut får man upp ett fönster där mna behöver bekräfta utloggning
        int svar = JOptionPane.showConfirmDialog(this, "Vill du logga ut?", "Bekräfta", JOptionPane.YES_NO_OPTION);
        //Om man väljer jag loggas man ut
        if (svar == JOptionPane.YES_OPTION) {
            this.dispose();
            MainFrame nyMainFrame = new MainFrame(idb);
            nyMainFrame.setVisible(true);
        }
    }


    public void hanteraAnstallda(){
        try{
            String hamtaAnstallda = "select Behorighet from Anstalld where Epost = '" + txtfEmail.getText() + "';";
            String behorighet = idb.fetchSingle(hamtaAnstallda); 
                if(behorighet.equals("1")){
                    hanteraAnstallda.setVisible(false);
                }
                else if(behorighet.equals("2")){                           
                    hanteraAnstallda.setVisible(true);
                }
        }
        catch(InfException ex){
            System.out.println(ex);
        }
    }
    
    public void addPanelToCardLayout(JPanel panel, String name) {
        jPanel1.add(panel, name);
    }

    public void showPanel(String name) {
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, name);
    }
   
    

   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pswfLosenord = new javax.swing.JPasswordField();
        btnLoggaIn = new javax.swing.JButton();
        lblFelMeddelande = new javax.swing.JLabel();
        lblInloggning = new javax.swing.JLabel();
        txtfEmail = new javax.swing.JTextField();
        lblEpost = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        logotyp = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOrdrar = new javax.swing.JMenu();
        seOrdrarItem = new javax.swing.JMenuItem();
        skapaNyOrderItem = new javax.swing.JMenuItem();
        skapaNySpecialOrderItem = new javax.swing.JMenuItem();
        skapaNyFraktsedel = new javax.swing.JMenu();
        seAllaLagerfordaProdukter = new javax.swing.JMenu();
        forsalningsstatistik = new javax.swing.JMenu();
        visaKalender = new javax.swing.JMenu();
        hanteraAnstallda = new javax.swing.JMenu();
        seAllaKunder = new javax.swing.JMenu();
        installningar = new javax.swing.JMenu();
        loggaUt = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        pswfLosenord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pswfLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswfLosenordActionPerformed(evt);
            }
        });

        btnLoggaIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });

        lblFelMeddelande.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblFelMeddelande.setText("Felaktig inloggning! ");
        lblFelMeddelande.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFelMeddelande.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblFelMeddelandeComponentHidden(evt);
            }
        });

        lblInloggning.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblInloggning.setText("Inloggning");

        txtfEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblEpost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEpost.setText("E-post");

        lblLosenord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLosenord.setText("Lösenord");

        logotyp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hattmakarna/hattmakarna_logotyp.png"))); // NOI18N

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        menuOrdrar.setText("Ordrar");

        seOrdrarItem.setText("Se alla ordrar");
        seOrdrarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seOrdrarItemActionPerformed(evt);
            }
        });
        menuOrdrar.add(seOrdrarItem);

        skapaNyOrderItem.setText("Skapa ny order");
        skapaNyOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skapaNyOrderItemActionPerformed(evt);
            }
        });
        menuOrdrar.add(skapaNyOrderItem);

        skapaNySpecialOrderItem.setText("Skapa ny specialorder");
        skapaNySpecialOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skapaNySpecialOrderItemActionPerformed(evt);
            }
        });
        menuOrdrar.add(skapaNySpecialOrderItem);

        jMenuBar1.add(menuOrdrar);

        skapaNyFraktsedel.setText("Skapa ny fraktsedel");
        skapaNyFraktsedel.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                skapaNyFraktsedelMenuSelected(evt);
            }
        });

        seAllaLagerfordaProdukter.setText("Se alla lagerförda produkter");
        seAllaLagerfordaProdukter.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                seAllaLagerfordaProdukterMenuSelected(evt);
            }
        });
        skapaNyFraktsedel.add(seAllaLagerfordaProdukter);

        jMenuBar1.add(skapaNyFraktsedel);

        forsalningsstatistik.setText("Försäljningsstatistik");
        forsalningsstatistik.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                forsalningsstatistikMenuSelected(evt);
            }
        });
        jMenuBar1.add(forsalningsstatistik);

        visaKalender.setText("Visa Kalenderschema");
        visaKalender.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                visaKalenderMenuSelected(evt);
            }
        });
        jMenuBar1.add(visaKalender);

        hanteraAnstallda.setText("Hantera anställda");
        hanteraAnstallda.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                hanteraAnstalldaMenuSelected(evt);
            }
        });
        jMenuBar1.add(hanteraAnstallda);

        seAllaKunder.setText("Se alla kunder");
        seAllaKunder.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                seAllaKunderMenuSelected(evt);
            }
        });
        jMenuBar1.add(seAllaKunder);

        installningar.setText("Inställningar");
        installningar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                installningarMenuSelected(evt);
            }
        });

        loggaUt.setText("Logga ut");
        loggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loggaUtActionPerformed(evt);
            }
        });
        installningar.add(loggaUt);

        jMenuBar1.add(installningar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(385, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblInloggning))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pswfLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lblFelMeddelande))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(536, 536, 536))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(logotyp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1541, 1541, 1541)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(logotyp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInloggning, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pswfLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLosenord))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoggaIn)
                        .addGap(127, 127, 127)
                        .addComponent(lblFelMeddelande)))
                .addContainerGap(304, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visaKalenderMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_visaKalenderMenuSelected
        // TODO add your handling code here:
        // Kontrollera om "inlogg" redan finns
        // Skapa SeAllaOrdrar-panelen som vanligt
        kalenderPanel = new KalenderSchemaRatt(idb, txtfEmail.getText());

        // Skapa en wrapper-panel med centrerad layout
        JPanel wrapper = new JPanel(new GridBagLayout()); // centrerar automatiskt sitt innehåll
        wrapper.add(kalenderPanel); // lägg SeAllaOrdrar i mitten

        // Lägg till wrappern i card layout-systemet istället för SeAllaOrdrar direkt
        addPanelToCardLayout(wrapper, "Kalenderschema");

        // Visa
        showPanel("Kalenderschema");
        
    }//GEN-LAST:event_visaKalenderMenuSelected

    private void seAllaKunderMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_seAllaKunderMenuSelected
        // TODO add your handling code here:
        allaKunderPanel = new SeAllaKunder(idb, txtfEmail.getText());

        // Skapa en wrapper-panel med centrerad layout
        JPanel wrapper = new JPanel(new GridBagLayout()); // centrerar automatiskt sitt innehåll
        wrapper.add(allaKunderPanel); // lägg SeAllaOrdrar i mitten

        // Lägg till wrappern i card layout-systemet istället för SeAllaOrdrar direkt
        addPanelToCardLayout(wrapper, "Alla kunder");

        // Visa
        showPanel("Alla kunder");
    }//GEN-LAST:event_seAllaKunderMenuSelected

    private void seAllaLagerfordaProdukterMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_seAllaLagerfordaProdukterMenuSelected
        // TODO add your handling code here:       
        allaLagerfordaProdukterPanel = new SeAllaLagerfordaProdukter(idb, txtfEmail.getText());

        // Skapa en wrapper-panel med centrerad layout
        JPanel wrapper = new JPanel(new GridBagLayout()); // centrerar automatiskt sitt innehåll
        wrapper.add(allaLagerfordaProdukterPanel); // lägg SeAllaOrdrar i mitten

        // Lägg till wrappern i card layout-systemet istället för SeAllaOrdrar direkt
        addPanelToCardLayout(wrapper, "Alla lagerförda produkter");

        // Visa
        showPanel("Alla lagerförda produkter");
    }//GEN-LAST:event_seAllaLagerfordaProdukterMenuSelected

    private void forsalningsstatistikMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_forsalningsstatistikMenuSelected
        // TODO add your handling code here:
        seForsaljningsstatistikPanel = new SeForsaljningsstatistik(idb, txtfEmail.getText());

        // Skapa en wrapper-panel med centrerad layout
        JPanel wrapper = new JPanel(new GridBagLayout()); // centrerar automatiskt sitt innehåll
        wrapper.add(seForsaljningsstatistikPanel); // lägg SeAllaOrdrar i mitten

        // Lägg till wrappern i card layout-systemet istället för SeAllaOrdrar direkt
        addPanelToCardLayout(wrapper, "Se försäljningsstatistik");

        // Visa
        showPanel("Se försäljningsstatistik");
    }//GEN-LAST:event_forsalningsstatistikMenuSelected

    private void hanteraAnstalldaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_hanteraAnstalldaMenuSelected
        // TODO add your handling code here:
        
        
        hanteraAllaAnstalldaPanel = new HanteraAllaAnstallda(idb, txtfEmail.getText());

        // Skapa en wrapper-panel med centrerad layout
        JPanel wrapper = new JPanel(new GridBagLayout()); // centrerar automatiskt sitt innehåll
        wrapper.add(hanteraAllaAnstalldaPanel); // lägg SeAllaOrdrar i mitten

        // Lägg till wrappern i card layout-systemet istället för SeAllaOrdrar direkt
        addPanelToCardLayout(wrapper, "Hantera anställda");

        // Visa
        showPanel("Hantera anställda");
        
    }//GEN-LAST:event_hanteraAnstalldaMenuSelected

    private void installningarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_installningarMenuSelected
        // TODO add your handling code here:
        
    }//GEN-LAST:event_installningarMenuSelected

    private void loggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loggaUtActionPerformed
        // TODO add your handling code here:
        loggaUt();
    }//GEN-LAST:event_loggaUtActionPerformed

    private void pswfLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswfLosenordActionPerformed

    }//GEN-LAST:event_pswfLosenordActionPerformed

    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        //Hämtar användarinmatning
        String ePost = txtfEmail.getText();
    char[] losenord = pswfLosenord.getPassword();
    String losen = new String(losenord);

    try {
        lblFelMeddelande.setVisible(false);

        if (!Validering.faltInteTomt(ePost) || !Validering.faltInteTomt(losen)) {
            lblFelMeddelande.setText("Inget av fälten får vara tomma");
            lblFelMeddelande.setVisible(true);
            return;
        }

        if (!Validering.valideringEmail(ePost)) {
            lblFelMeddelande.setText("Ange korrekt format för e-postadress");
            lblFelMeddelande.setVisible(true);
            return;
        }

        if (!Validering.finnsEpost(ePost, idb)) {
            lblFelMeddelande.setText("Finns ingen användare med denna epost");
            lblFelMeddelande.setVisible(true);
            return;
        }

        if (!Validering.arLosenordKorrekt(ePost, losen, idb)) {
            lblFelMeddelande.setText("Fel lösenord för denna användare");
            lblFelMeddelande.setVisible(true);
            pswfLosenord.setText("");
            return;
        }

        // Hämta behörighet från databasen
        String behorighetQuery = "SELECT Behorighet FROM Anstalld WHERE Epost = '" + ePost + "'";
        String behorighet = idb.fetchSingle(behorighetQuery);

        // Dölj inloggningskomponenter
        lblInloggning.setVisible(false);
        lblEpost.setVisible(false);
        txtfEmail.setVisible(false);
        lblLosenord.setVisible(false);
        pswfLosenord.setVisible(false);
        btnLoggaIn.setVisible(false);
        lblFelMeddelande.setVisible(false);

        // Visa menyrad
        jMenuBar1.setVisible(true);
        logotyp.setVisible(false);

        // Visa "Hantera anställda"-menyn enbart för behörighet 2
        if (!"2".equals(behorighet)) {
            hanteraAnstallda.setVisible(false); // jMenu9 = Hantera anställda
        } else {
            hanteraAnstallda.setVisible(true);
        }

        // Visa valfri startpanel
        hanteraAnstallda();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Något gick fel: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnLoggaInActionPerformed

    private void lblFelMeddelandeComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblFelMeddelandeComponentHidden

    }//GEN-LAST:event_lblFelMeddelandeComponentHidden

    private void skapaNyFraktsedelMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_skapaNyFraktsedelMenuSelected
     // TODO add your handling code here:
        fraktsedelPanel = new SkapaNyFraktsedel(idb, txtfEmail.getText());

        // Skapa en wrapper-panel med centrerad layout
        JPanel wrapper = new JPanel(new GridBagLayout()); // centrerar automatiskt sitt innehåll
        wrapper.add(fraktsedelPanel); // lägg SeAllaOrdrar i mitten

        // Lägg till wrappern i card layout-systemet istället för SeAllaOrdrar direkt
        addPanelToCardLayout(wrapper, "Fraktsedel");

        // Visa
        showPanel("Fraktsedel");
    }//GEN-LAST:event_skapaNyFraktsedelMenuSelected

    private void seOrdrarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seOrdrarItemActionPerformed
        // TODO add your handling code here:
        allaOrdrarPanel = new SeAllaOrdrar(idb, txtfEmail.getText());

        // Skapa en wrapper-panel med centrerad layout
        JPanel wrapper = new JPanel(new GridBagLayout()); // centrerar automatiskt sitt innehåll
        wrapper.add(allaOrdrarPanel); // lägg SeAllaOrdrar i mitten

        // Lägg till wrappern i card layout-systemet istället för SeAllaOrdrar direkt
        addPanelToCardLayout(wrapper, "Alla ordrar");

        // Visa
        showPanel("Alla ordrar");
    }//GEN-LAST:event_seOrdrarItemActionPerformed

    private void skapaNyOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skapaNyOrderItemActionPerformed
        // TODO add your handling code here:
        nyOrderPanel = new SkapaNyOrder(idb, txtfEmail.getText());

        // Skapa en wrapper-panel med centrerad layout
        JPanel wrapper = new JPanel(new GridBagLayout()); // centrerar automatiskt sitt innehåll
        wrapper.add(nyOrderPanel); // lägg SeAllaOrdrar i mitten

        // Lägg till wrappern i card layout-systemet istället för SeAllaOrdrar direkt
        addPanelToCardLayout(wrapper, "Skapa ny order");

        // Visa
        showPanel("Skapa ny order");
    }//GEN-LAST:event_skapaNyOrderItemActionPerformed

    private void skapaNySpecialOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skapaNySpecialOrderItemActionPerformed
        // TODO add your handling code here:
        skapaSpecialOrderPanel = new SkapaNySpecialOrder(idb, txtfEmail.getText());

        // Skapa en wrapper-panel med centrerad layout
        JPanel wrapper = new JPanel(new GridBagLayout()); // centrerar automatiskt sitt innehåll
        wrapper.add(skapaSpecialOrderPanel); // lägg SeAllaOrdrar i mitten

        // Lägg till wrappern i card layout-systemet istället för SeAllaOrdrar direkt
        addPanelToCardLayout(wrapper, "Skapa ny specialorder");

        // Visa
        showPanel("Skapa ny specialorder");
    }//GEN-LAST:event_skapaNySpecialOrderItemActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JMenu forsalningsstatistik;
    private javax.swing.JMenu hanteraAnstallda;
    private javax.swing.JMenu installningar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelMeddelande;
    private javax.swing.JLabel lblInloggning;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JMenuItem loggaUt;
    private javax.swing.JLabel logotyp;
    private javax.swing.JMenu menuOrdrar;
    private javax.swing.JPasswordField pswfLosenord;
    private javax.swing.JMenu seAllaKunder;
    private javax.swing.JMenu seAllaLagerfordaProdukter;
    private javax.swing.JMenuItem seOrdrarItem;
    private javax.swing.JMenu skapaNyFraktsedel;
    private javax.swing.JMenuItem skapaNyOrderItem;
    private javax.swing.JMenuItem skapaNySpecialOrderItem;
    private javax.swing.JTextField txtfEmail;
    private javax.swing.JMenu visaKalender;
    // End of variables declaration//GEN-END:variables
}
