/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;

import java.util.HashMap;
import java.util.List;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mejaa
 */
public class SeForsaljningsstatistik extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form SeForsaljningsstatistik
     */
    public SeForsaljningsstatistik(InfDB idb, String ePost) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = ePost;
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Namn", "Pris", "Antal", "Datum"}, 0
        );
        jTable1.setModel(model);

        visaLevereradeStandardhattar();
    }

    private void visaLevereradeStandardhattar() {
        try {
            String fraga = "SELECT sp.Namn AS Namn, sp.Pris AS Pris, oi.AntalProdukter AS Antal, b.Datum AS Datum "
                    + "FROM OrderItem oi "
                    + "JOIN Bestallning b ON oi.BestallningID = b.BestallningID "
                    + "JOIN StandardProdukt sp ON oi.StandardProduktID = sp.StandardProduktID "
                    + "WHERE b.Status = 'Levererad'";

            List<HashMap<String, String>> resultat = idb.fetchRows(fraga);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Rensa gamla rader

            if (resultat != null) {
                for (HashMap<String, String> rad : resultat) {
                    model.addRow(new Object[]{
                        rad.get("Namn"),
                        rad.get("Pris"),
                        rad.get("AntalProdukter"),
                        rad.get("Datum")
                    });
                }
            } else {
                System.out.println("Inga levererade standardhattar hittades.");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Kunde inte hämta statistik:" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtHatt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSortera = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSokDatumFran = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSokDatumTill = new javax.swing.JTextField();
        btnSorteraDatum = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        btnSummera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Försäljningsstatistik");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hattsort", "Pris", "Antal", "Datum"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtHatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHattActionPerformed(evt);
            }
        });

        jLabel2.setText("Sortera efter hatt");

        btnSortera.setText("Sortera");
        btnSortera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorteraActionPerformed(evt);
            }
        });

        jLabel3.setText("Sök efter datum");

        txtSokDatumFran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSokDatumFranActionPerformed(evt);
            }
        });

        jLabel4.setText("Från:");

        jLabel5.setText("Till:");

        btnSorteraDatum.setText("Sortera");
        btnSorteraDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorteraDatumActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSummera.setText("Summera");
        btnSummera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummeraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(130, 130, 130)
                        .addComponent(btnTillbaka))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(btnSummera))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(btnSortera, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSokDatumFran, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSokDatumTill, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSorteraDatum))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtHatt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addGap(133, 133, 133))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTillbaka, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtHatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSokDatumFran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtSokDatumTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSorteraDatum)
                    .addComponent(btnSummera)
                    .addComponent(btnSortera))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        //Kod för tillbaka kappen som skickar tillbaka användaren till huvudmenyn. 
        new HuvudMeny(idb, inloggadAnvandare).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void txtHattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHattActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHattActionPerformed

    private void btnSorteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorteraActionPerformed
        String hatt = txtHatt.getText().trim();
        try {
            String fraga = "SELECT sp.Namn AS Namn, sp.Pris AS Pris, oi.AntalProdukter AS Antal, b.Datum AS Datum "
                    + "FROM OrderItem oi "
                    + "JOIN Bestallning b ON oi.BestallningID = b.BestallningID "
                    + "JOIN StandardProdukt sp ON oi.StandardProduktID = sp.StandardProduktID "
                    + "WHERE b.Status = 'Levererad' AND sp.Namn = '" + hatt + "'";

            List<HashMap<String, String>> resultat = idb.fetchRows(fraga);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Rensa gamla rader

            if (resultat != null) {
                for (HashMap<String, String> rad : resultat) {
                    model.addRow(new Object[]{
                        rad.get("Namn"),
                        rad.get("Pris"),
                        rad.get("AntalProdukter"),
                        rad.get("Datum")
                    });
                }
            } else {
                JOptionPane.showMessageDialog(this, "Inga levererade standardhattar hittades.");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Kunde inte hitta den hatten" + e.getMessage());
        }

    }//GEN-LAST:event_btnSorteraActionPerformed

    private void btnSummeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummeraActionPerformed
        String hatt = txtHatt.getText();

        try {
            String fraga = "SELECT sp.Namn AS Namn, sp.Pris AS Pris, oi.AntalProdukter AS Antal, b.Datum AS Datum "
                    + "FROM OrderItem oi "
                    + "JOIN Bestallning b ON oi.BestallningID = b.BestallningID "
                    + "JOIN StandardProdukt sp ON oi.StandardProduktID = sp.StandardProduktID "
                    + "WHERE b.Status = 'Levererad' AND sp.Namn = '" + hatt + "'";

            List<HashMap<String, String>> resultat = idb.fetchRows(fraga);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // 🧹 Rensa tabellen innan summering

            if (resultat != null && !resultat.isEmpty()) {
                int totalAntal = 0;
                double totalPris = 0;

                for (HashMap<String, String> rad : resultat) {
                    String antalStr = rad.get("AntalProdukter");
                    String prisStr = rad.get("Pris");

                    if (antalStr != null && prisStr != null) {
                        int antal = Integer.parseInt(antalStr);
                        double pris = Double.parseDouble(prisStr);
                        totalAntal += antal;
                        totalPris += pris * antal;
                    } else {
                        System.out.println("Null-värde hittat! Antal: " + antalStr + ", Pris: " + prisStr);
                    }
                }

                // 💡 Lägg till EN rad med summering
                model.addRow(new Object[]{
                    "Totalt för: " + hatt,
                    String.format("%.2f kr", totalPris),
                    totalAntal,
                    "" // Datumfältet tomt
                });

            } else {
                JOptionPane.showMessageDialog(this, "Inga levererade ordrar hittades för produkten.");
            }

        } catch (InfException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Fel vid summering: " + e.getMessage());
        }


    }//GEN-LAST:event_btnSummeraActionPerformed

    private void btnSorteraDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorteraDatumActionPerformed
     String fran = txtSokDatumFran.getText();
     String till = txtSokDatumTill.getText();
        try {
            String fraga = "SELECT sp.Namn AS Namn, sp.Pris AS Pris, oi.AntalProdukter AS Antal, b.Datum AS Datum "
                    + "FROM OrderItem oi "
                    + "JOIN Bestallning b ON oi.BestallningID = b.BestallningID "
                    + "JOIN StandardProdukt sp ON oi.StandardProduktID = sp.StandardProduktID "
                    + "WHERE b.Status = 'Levererad' AND b.Datum => '" +fran+ "' AND b.Datum <= '" +till+"'";

            List<HashMap<String, String>> resultat = idb.fetchRows(fraga);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Rensa gamla rader

            if (resultat != null) {
                for (HashMap<String, String> rad : resultat) {
                    model.addRow(new Object[]{
                        rad.get("Namn"),
                        rad.get("Pris"),
                        rad.get("AntalProdukter"),
                        rad.get("Datum")
                    });
                }
            } else {
                JOptionPane.showMessageDialog(this, "Inga levererade hattar hittades inom det spannet.");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Kunde inte hitta den hatten" + e.getMessage());
        }

                                 
    }//GEN-LAST:event_btnSorteraDatumActionPerformed

    private void txtSokDatumFranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSokDatumFranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSokDatumFranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSortera;
    private javax.swing.JButton btnSorteraDatum;
    private javax.swing.JButton btnSummera;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtHatt;
    private javax.swing.JTextField txtSokDatumFran;
    private javax.swing.JTextField txtSokDatumTill;
    // End of variables declaration//GEN-END:variables
}
