/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hattmakarna;

import java.util.HashMap;
import java.util.List;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adam
 */
public class SeForsaljningsstatistik extends javax.swing.JPanel {

    private InfDB idb;
    private String inloggadAnvandare;
    /**
     * Creates new form SeForsaljningsstatistik
     */
    public SeForsaljningsstatistik(InfDB idb, String ePost) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = ePost;
        //DefaultTableModel model = new DefaultTableModel(new Object[]{"Namn", "Pris", "Antal", "Datum"});
        //jTable1.setModel(model);

        visaLevereradeStandardhattar();
    }

        private void visaLevereradeStandardhattar() {
        try {
            String fraga = "SELECT sp.Namn AS Namn, sp.Pris AS Pris, oi.AntalProdukter AS Antal, b.Datum AS Datum "
                    + "FROM OrderItem oi "
                    + "JOIN Bestallning b ON oi.BestallningID = b.BestallningID "
                    + "JOIN StandardProdukt sp ON oi.StandardProduktID = sp.StandardProduktID "
                    + "WHERE b.Status = 'Levererad'";

            List<HashMap<String, String>> resultat = idb.fetchRows(fraga);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Rensa gamla rader

            if (resultat != null) {
                for (HashMap<String, String> rad : resultat) {
                    model.addRow(new Object[]{
                        rad.get("Namn"),
                        rad.get("Pris"),
                        rad.get("AntalProdukter"),
                        rad.get("Datum")
                    });
                }
            } else {
                System.out.println("Inga levererade standardhattar hittades.");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Kunde inte hämta statistik:" + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtHatt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSokDatumFran = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSokDatumTill = new javax.swing.JTextField();
        btnFiltrera = new javax.swing.JButton();
        btnSummera = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Försäljningsstatistik");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Namn", "Pris", "Antal", "Datum"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Filtrera efter produkt");

        txtHatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHattActionPerformed(evt);
            }
        });

        jLabel3.setText("Filtrera efter datum");

        jLabel4.setText("Från:");

        jLabel5.setText("Till:");

        txtSokDatumTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSokDatumTillActionPerformed(evt);
            }
        });

        btnFiltrera.setText("Filtrera");
        btnFiltrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltreraActionPerformed(evt);
            }
        });

        btnSummera.setText("Summera");
        btnSummera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummeraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(129, 129, 129)
                        .addComponent(btnTillbaka)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtHatt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSokDatumFran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSokDatumTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFiltrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnSummera)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnTillbaka))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtSokDatumFran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSokDatumTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrera)
                    .addComponent(btnSummera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHattActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHattActionPerformed

    private void txtSokDatumTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSokDatumTillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSokDatumTillActionPerformed

    private void btnSummeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummeraActionPerformed
        String hatt = txtHatt.getText();
        try {
            String fraga = "SELECT sp.Namn AS Namn, sp.Pris AS Pris, oi.AntalProdukter AS Antal, b.Datum AS Datum "
                    + "FROM OrderItem oi "
                    + "JOIN Bestallning b ON oi.BestallningID = b.BestallningID "
                    + "JOIN StandardProdukt sp ON oi.StandardProduktID = sp.StandardProduktID "
                    + "WHERE b.Status = 'Levererad' AND sp.Namn = '" + hatt + "'";

            List<HashMap<String, String>> resultat = idb.fetchRows(fraga);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Rensa tabellen innan summering

            if (resultat != null && !resultat.isEmpty()) {
                int totalAntal = 0;
                double totalPris = 0;

                for (HashMap<String, String> rad : resultat) {
                    String antalStr = rad.get("AntalProdukter");
                    String prisStr = rad.get("Pris");

                    if (antalStr != null && prisStr != null) {
                        int antal = Integer.parseInt(antalStr);
                        double pris = Double.parseDouble(prisStr);
                        totalAntal += antal;
                        totalPris += pris * antal;
                    } else {
                        System.out.println("Null-värde hittat! Antal: " + antalStr + ", Pris: " + prisStr);
                    }
                }

                //Lägg till EN rad med summering
                model.addRow(new Object[]{
                    "Totalt för: " + hatt,
                    String.format("%.2f kr", totalPris),
                    totalAntal,
                    "" // Datumfältet tomt
                });

            } else {
                JOptionPane.showMessageDialog(this, "Inga levererade ordrar hittades för produkten.");
            }

        } catch (InfException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Fel vid summering: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSummeraActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        //XD
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnFiltreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltreraActionPerformed
        String hatt = txtHatt.getText().trim();
        String fran = txtSokDatumFran.getText().trim();
        String till = txtSokDatumTill.getText().trim();

        //Validera eventuella datum
        if ((!fran.isEmpty() && !Validering.valideringDatum(fran))
                || (!till.isEmpty() && !Validering.valideringDatum(till))) {
            JOptionPane.showMessageDialog(this, "Datum måste anges i formatet ÅÅÅÅ-MM-DD.");
            return;
        }

        try {
            //Bygg basfråga
            StringBuilder fraga = new StringBuilder(
                    "SELECT sp.Namn AS Namn, sp.Pris AS Pris, oi.AntalProdukter AS Antal, b.Datum AS Datum "
                    + "FROM OrderItem oi "
                    + "JOIN Bestallning b ON oi.BestallningID = b.BestallningID "
                    + "JOIN StandardProdukt sp ON oi.StandardProduktID = sp.StandardProduktID "
                    + "WHERE b.Status = 'Levererad'"
            );

            // Lägg till filtrering om fält är ifyllda
            if (!hatt.isEmpty()) {
                fraga.append(" AND sp.Namn = '").append(hatt).append("'");
            }
            if (!fran.isEmpty()) {
                fraga.append(" AND b.Datum >= '").append(fran).append("'");
            }
            if (!till.isEmpty()) {
                fraga.append(" AND b.Datum <= '").append(till).append("'");
            }

            List<HashMap<String, String>> resultat = idb.fetchRows(fraga.toString());

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Töm tabellen

            if (resultat != null && !resultat.isEmpty()) {
                for (HashMap<String, String> rad : resultat) {
                    model.addRow(new Object[]{
                        rad.get("Namn"),
                        rad.get("Pris"),
                        rad.get("Antal"),
                        rad.get("Datum")
                    });
                }
            } else {
                JOptionPane.showMessageDialog(this, "Inga resultat hittades.");
            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid sökning: " + e.getMessage());
        }
    }//GEN-LAST:event_btnFiltreraActionPerformed

    private void gamlaSorteraDatum(){
//             String fran = txtSokDatumFran.getText();
//     String till = txtSokDatumTill.getText();
//        try {
//            String fraga = "SELECT sp.Namn AS Namn, sp.Pris AS Pris, oi.AntalProdukter AS Antal, b.Datum AS Datum "
//                    + "FROM OrderItem oi "
//                    + "JOIN Bestallning b ON oi.BestallningID = b.BestallningID "
//                    + "JOIN StandardProdukt sp ON oi.StandardProduktID = sp.StandardProduktID "
//                    + "WHERE b.Status = 'Levererad' AND b.Datum => '" +fran+ "' AND b.Datum <= '" +till+"'";
//
//            List<HashMap<String, String>> resultat = idb.fetchRows(fraga);
//
//            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//            model.setRowCount(0); // Rensa gamla rader
//
//            if (resultat != null) {
//                for (HashMap<String, String> rad : resultat) {
//                    model.addRow(new Object[]{
//                        rad.get("Namn"),
//                        rad.get("Pris"),
//                        rad.get("AntalProdukter"),
//                        rad.get("Datum")
//                    });
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Inga levererade hattar hittades inom det spannet.");
//            }
//        } catch (InfException e) {
//            JOptionPane.showMessageDialog(null, "Kunde inte hitta den hatten" + e.getMessage());
//        }
    }
    
    private void gamlaSortera(){
//        String hatt = txtHatt.getText().trim();
//        try {
//            String fraga = "SELECT sp.Namn AS Namn, sp.Pris AS Pris, oi.AntalProdukter AS Antal, b.Datum AS Datum "
//                    + "FROM OrderItem oi "
//                    + "JOIN Bestallning b ON oi.BestallningID = b.BestallningID "
//                    + "JOIN StandardProdukt sp ON oi.StandardProduktID = sp.StandardProduktID "
//                    + "WHERE b.Status = 'Levererad' AND sp.Namn = '" + hatt + "'";
//
//            List<HashMap<String, String>> resultat = idb.fetchRows(fraga);
//
//            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//            model.setRowCount(0); // Rensa gamla rader
//
//            if (resultat != null) {
//                for (HashMap<String, String> rad : resultat) {
//                    model.addRow(new Object[]{
//                        rad.get("Namn"),
//                        rad.get("Pris"),
//                        rad.get("AntalProdukter"),
//                        rad.get("Datum")
//                    });
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Inga levererade standardhattar hittades.");
//            }
//        } catch (InfException e) {
//            JOptionPane.showMessageDialog(null, "Kunde inte hitta den hatten" + e.getMessage());
//        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrera;
    private javax.swing.JButton btnSummera;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtHatt;
    private javax.swing.JTextField txtSokDatumFran;
    private javax.swing.JTextField txtSokDatumTill;
    // End of variables declaration//GEN-END:variables
}
