/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;
import oru.inf.InfDB; 
import oru.inf.InfException; 
import javax.swing.JOptionPane; 
import java.util.Random; 
import java.util.ArrayList; 
import java.sql.PreparedStatement; 
import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.LocalDate;
import javax.swing.*;
/**
 *
 * @author Elin
 */
public class SkapaVanligOrder extends javax.swing.JFrame {

        private HuvudMeny oldWindow; 
        private InfDB idb; 
        private String inloggadAnvandare; 
    /**
     * Creates new form SkapaVanligOrder
     */
    public SkapaVanligOrder(InfDB idb, String ePost) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = ePost;
        cbKundnummer.removeAllItems();
        fyllKundIDComboBox();
        //this.oldWindow = oldWindow; 
    }
    
    private void nollställTextfält() {
        txtfOrdernummer.setText("");
        txtfDatum.setText(""); 
        txtfPris.setText(""); 
        txtfNamn.setText(""); 
        txtfPris2.setText(""); 
        txtfAntal.setText(""); 
    }
    
    private void fyllKundIDComboBox(){
        try {
            cbKundnummer.removeAllItems();  // Rensar alla tidigare objekt
            cbKundnummer.addItem("Välj KundID");  // Lägg till "Välj KundID" som första alternativ
            ArrayList<String> kundIDLista = idb.fetchColumn("SELECT KundID FROM kund");
            for (String id : kundIDLista) {
                cbKundnummer.addItem(id);  // Lägg till de faktiska kundID:n
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Fel vid hämtning av KundID: " + e.getMessage());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblOrdernummer = new javax.swing.JLabel();
        lblKundnummer = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblPris = new javax.swing.JLabel();
        txtfOrdernummer = new javax.swing.JTextField();
        txtfDatum = new javax.swing.JTextField();
        txtfPris = new javax.swing.JTextField();
        btnSpara = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        lblExpressleverans = new javax.swing.JLabel();
        cbJa = new javax.swing.JCheckBox();
        lblProduktlista = new javax.swing.JLabel();
        lblArtikelnummer = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblPris2 = new javax.swing.JLabel();
        lblAntal = new javax.swing.JLabel();
        txtfNamn = new javax.swing.JTextField();
        txtfPris2 = new javax.swing.JTextField();
        txtfAntal = new javax.swing.JTextField();
        btnGenerera = new javax.swing.JButton();
        cbKundnummer = new javax.swing.JComboBox<>();
        cbNamn = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Skapa order");

        lblOrdernummer.setText("Ordernummer:");

        lblKundnummer.setText("Kundnummer:");

        lblDatum.setText("Datum:");

        lblPris.setText("Totala priset: ");

        txtfOrdernummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfOrdernummerActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        lblExpressleverans.setText("Expressleverans?");

        cbJa.setText("Ja");
        cbJa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJaActionPerformed(evt);
            }
        });

        lblProduktlista.setText("Produktlista");

        lblArtikelnummer.setText("Artikelnummer");

        lblNamn.setText("Namn");

        lblPris2.setText("Pris");

        lblAntal.setText("Antal");

        btnGenerera.setText("Generera");
        btnGenerera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenereraActionPerformed(evt);
            }
        });

        cbKundnummer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNamn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTillbaka)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblExpressleverans)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbJa))
                            .addComponent(btnSpara))
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblOrdernummer)
                        .addComponent(lblKundnummer)
                        .addComponent(lblDatum)
                        .addComponent(lblPris)
                        .addComponent(lblProduktlista)
                        .addComponent(lblNamn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfOrdernummer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblArtikelnummer))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                        .addComponent(txtfPris2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(lblPris2))
                                            .addComponent(btnGenerera))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(txtfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfPris, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbKundnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAntal)
                    .addComponent(txtfAntal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrdernummer)
                    .addComponent(txtfOrdernummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpara)
                    .addComponent(btnGenerera))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKundnummer)
                            .addComponent(btnTillbaka)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbKundnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatum)
                    .addComponent(txtfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPris)
                    .addComponent(txtfPris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpressleverans)
                    .addComponent(cbJa))
                .addGap(9, 9, 9)
                .addComponent(lblProduktlista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(lblPris2)
                    .addComponent(lblAntal)
                    .addComponent(lblArtikelnummer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfPris2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfAntal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbJaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJaActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_cbJaActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        //Kod för tillbaka kappen som skickar tillbaka användaren till huvudmenyn. 
        new HuvudMeny(idb, inloggadAnvandare).setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        {                                         
        // Kontrollera om "Välj KundID" är valt
        String kundnummer = cbKundnummer.getSelectedItem().toString();
        if ("Välj KundID".equals(kundnummer)) {
            JOptionPane.showMessageDialog(null, "Vänligen välj ett giltigt KundID.");
            return;  // Stoppar vidare exekvering om ogiltigt alternativ är valt
        }

        // Hämtar övriga värden från textfälten
        String datum = txtfDatum.getText();  // Hämtar datumet från textfältet
        String pris = txtfPris.getText(); 
        String ordernummer = txtfOrdernummer.getText(); 
        String namn = txtfNamn.getText(); 
        String pris2 = txtfPris2.getText(); 
        String antal = txtfAntal.getText(); 

        // Validera datumet
        if (!Validering.valideringDatum(datum)) {
            JOptionPane.showMessageDialog(null, "Ogiltigt datumformat. Använd formatet yyyy-MM-dd.");
            return;  // Stoppar vidare exekvering om datumet är ogiltigt
        }

        // SQL-fråga för att spara order
        String sqlFraga = "SELECT oi.OrderItemID AS Artikelnummer, b.KundID AS Kundnummer, b.Datum,(sp.Pris * oi.AntalProdukter) AS TotaltPris, b.BestallningID AS Ordernummer, sp.Namn AS ProduktNamn, sp.Pris AS ArtikelPris "
                + "FROM OrderItem oi JOIN Bestallning b ON oi.BestallningID = b.BestallningID JOIN StandardProdukt sp ON oi.StandardProduktID = sp.StandardProduktID UNION "
                + "SELECT oi.OrderItemID AS Artikelnummer, b.KundID AS Kundnummer, b.Datum, (sp2.Pris * oi.AntalProdukter) AS TotaltPris, b.BestallningID AS Ordernummer,"
                + "sp2.Modell AS ProduktNamn, sp2.Pris AS ArtikelPris FROM OrderItem oi JOIN Bestallning b ON oi.BestallningID = b.BestallningID JOIN SpecialProdukt sp2 ON oi.SpecialProduktID = sp2.SpecialProduktID";

        try {
            idb.insert(sqlFraga);
            JOptionPane.showMessageDialog(null,"Order sparad");
            System.out.println("Ordernummer: " + ordernummer + ", Artikel: " + namn + ", Pris: " + pris);
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Fel vid inhämtning av orderdata:" + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnSparaActionPerformed

    private void txtfOrdernummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfOrdernummerActionPerformed
     
    }//GEN-LAST:event_txtfOrdernummerActionPerformed

    private void btnGenereraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenereraActionPerformed
        // Kod som genererar ett unikt slumpmässigt ordernr för varje order som skapas.
        int langdOrdernr = 10;
        String allaTecken = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890";
        StringBuilder slumpatOrdernr = new StringBuilder();
        java.util.Random random = new java.util.Random();
        for (int i=0; i<langdOrdernr; i++) {
            int x = random.nextInt(allaTecken.length());
            slumpatOrdernr.append(allaTecken.charAt(x));
        }
        txtfOrdernummer.setText(slumpatOrdernr.toString());
    }//GEN-LAST:event_btnGenereraActionPerformed

    private void txtfDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDatumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkapaVanligOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkapaVanligOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkapaVanligOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkapaVanligOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //    new SkapaVanligOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerera;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JCheckBox cbJa;
    private javax.swing.JComboBox<String> cbKundnummer;
    private javax.swing.JComboBox<String> cbNamn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAntal;
    private javax.swing.JLabel lblArtikelnummer;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblExpressleverans;
    private javax.swing.JLabel lblKundnummer;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblOrdernummer;
    private javax.swing.JLabel lblPris;
    private javax.swing.JLabel lblPris2;
    private javax.swing.JLabel lblProduktlista;
    private javax.swing.JTextField txtfAntal;
    private javax.swing.JTextField txtfDatum;
    private javax.swing.JTextField txtfNamn;
    private javax.swing.JTextField txtfOrdernummer;
    private javax.swing.JTextField txtfPris;
    private javax.swing.JTextField txtfPris2;
    // End of variables declaration//GEN-END:variables
}
