/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB; 
import oru.inf.InfException; 

/**
 *
 * @author iftinserar
 */
public class SpecifikKund extends javax.swing.JFrame {
    private static InfDB idb;
    private String inloggadAnvandare;  
    private int kundID;
    /**
     * Creates new form SpecifikKund
     */
    public SpecifikKund(InfDB idb, String inloggadAnvandare, int kundID) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        this.kundID = kundID;
        initComponents();
        fyllKundDetaljer();
        setEditable(false); // Gör fälten icke-redigerbara vid start

    }

private void fyllKundDetaljer() {
    try {
        String query = "SELECT * FROM Kund WHERE KundID = " + kundID + ";";
        HashMap<String, String> kundData = idb.fetchRow(query);

        if (kundData != null) {
            txtKundID.setText(String.valueOf(kundID));
            txtFornamn.setText(kundData.get("Fornamn"));
            txtEfternamn.setText(kundData.get("Efternamn"));
            txtEpost.setText(kundData.get("Epost"));
            txtTelefonnummer.setText(kundData.get("Telefonnummer"));
            txtLeveransAdress.setText(kundData.get("LeveransAdress"));
            txtLeveransPostNr.setText(kundData.get("LeveransPostnummer"));
            txtLeveransOrt.setText(kundData.get("LeveransOrt"));
            txtLeveransLand.setText(kundData.get("LeveransLand"));
            txtFakturaAdress.setText(kundData.get("FakturaAdress"));
            txtFakturaPostNr.setText(kundData.get("FakturaPostnummer"));
            txtFakturaOrt.setText(kundData.get("FakturaOrt"));
            txtFakturaLand.setText(kundData.get("FakturaLand"));
        } else {
            JOptionPane.showMessageDialog(this, "Kunden kunde inte hittas.");
        }
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Ett fel inträffade vid hämtning av kundinfo: " + ex.getMessage());
    }
}

    
        // Gör alla textfält redigerbara eller inte
    private void setEditable(boolean editable) {
        txtFornamn.setEditable(editable);
        txtEfternamn.setEditable(editable);
        txtEpost.setEditable(editable);
        txtTelefonnummer.setEditable(editable);
        txtLeveransOrt.setEditable(editable);
        txtLeveransAdress.setEditable(editable);
        txtFakturaAdress.setEditable(editable);
        BtnSpara.setEnabled(editable); // Spara-knappen kan bara användas om fälten är redigerbara
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTelefonnummer = new javax.swing.JLabel();
        lblLeveransadress = new javax.swing.JLabel();
        BtnTaBort = new javax.swing.JButton();
        BtnRedigera = new javax.swing.JButton();
        BtnSpara = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        lblFakturaadress = new javax.swing.JLabel();
        txtKundID = new javax.swing.JTextField();
        txtFornamn = new javax.swing.JTextField();
        txtEfternamn = new javax.swing.JTextField();
        txtEpost = new javax.swing.JTextField();
        txtTelefonnummer = new javax.swing.JTextField();
        txtLeveransAdress = new javax.swing.JTextField();
        txtFakturaAdress = new javax.swing.JTextField();
        txtLeveransOrt = new javax.swing.JTextField();
        txtFakturaOrt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLeveransPostNr = new javax.swing.JLabel();
        lblFakturaPostNr = new javax.swing.JLabel();
        txtLeveransPostNr = new javax.swing.JTextField();
        txtFakturaPostNr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLeveransLand = new javax.swing.JTextField();
        txtFakturaLand = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Kund");

        lblFornamn.setText("Fornamn");

        lblEfternamn.setText("Efternamn");

        lblEpost.setText("E-post");

        lblTelefonnummer.setText("Telefonnummer");

        lblLeveransadress.setText("Leveransadress");

        BtnTaBort.setText("Ta bort");
        BtnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTaBortActionPerformed(evt);
            }
        });

        BtnRedigera.setText("Redigera");
        BtnRedigera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRedigeraActionPerformed(evt);
            }
        });

        BtnSpara.setText("Spara");
        BtnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSparaActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        lblFakturaadress.setText("Fakturaadress");

        txtKundID.setEnabled(false);

        jLabel2.setText("Ort");

        jLabel3.setText("Ort");

        lblLeveransPostNr.setText("Postnummer");

        lblFakturaPostNr.setText("Postnummer");

        jLabel4.setText("Land");

        jLabel5.setText("Land");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLeveransadress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLeveransAdress))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEfternamn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFornamn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKundID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFakturaadress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFakturaAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblEpost)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtEpost))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTelefonnummer)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLeveransPostNr)
                            .addComponent(lblFakturaPostNr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLeveransPostNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFakturaPostNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnTaBort)
                        .addGap(128, 128, 128)
                        .addComponent(BtnRedigera)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSpara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbaka)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtLeveransOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtFakturaOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLeveransLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFakturaLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(94, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtKundID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornamn)
                    .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfternamn)
                    .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonnummer)
                    .addComponent(txtTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLeveransadress)
                    .addComponent(txtLeveransAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLeveransOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblLeveransPostNr)
                    .addComponent(txtLeveransPostNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtLeveransLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFakturaadress)
                    .addComponent(txtFakturaAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFakturaOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblFakturaPostNr)
                    .addComponent(txtFakturaPostNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtFakturaLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTaBort)
                    .addComponent(BtnRedigera)
                    .addComponent(BtnSpara)
                    .addComponent(btnTillbaka))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
    new AllaKunder(idb, inloggadAnvandare).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void BtnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSparaActionPerformed
    // Hämta och validera fält som tidigare + nya
    String fornamn = txtFornamn.getText();
    String efternamn = txtEfternamn.getText();
    String epost = txtEpost.getText();
    String telefonnummer = txtTelefonnummer.getText();
    String leveransAdress = txtLeveransAdress.getText();
    String leveransPostNr = txtLeveransPostNr.getText();
    String leveransOrt = txtLeveransOrt.getText();
    String leveransLand = txtLeveransLand.getText();
    String fakturaAdress = txtFakturaAdress.getText();
    String fakturaPostNr = txtFakturaPostNr.getText();
    String fakturaOrt = txtFakturaOrt.getText();
    String fakturaLand = txtFakturaLand.getText();

    // Enkel validering (utöka vid behov)
    if (!Validering.valideringEmail(epost)) {
        JOptionPane.showMessageDialog(this, "Ogiltig e-postadress.");
        return;
    }
    if (!Validering.valideringTelefon(telefonnummer)) {
        JOptionPane.showMessageDialog(this, "Ogiltigt telefonnummer.");
        return;
    }
    if (fornamn.isEmpty() || efternamn.isEmpty() || leveransAdress.isEmpty() || leveransOrt.isEmpty() || fakturaAdress.isEmpty() || fakturaOrt.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Alla fält måste fyllas i.");
        return;
    }

    try {
        String updateQuery = "UPDATE Kund SET " +
            "Fornamn = '" + fornamn + "', " +
            "Efternamn = '" + efternamn + "', " +
            "Epost = '" + epost + "', " +
            "Telefonnummer = '" + telefonnummer + "', " +
            "LeveransAdress = '" + leveransAdress + "', " +
            "LeveransPostnummer = '" + leveransPostNr + "', " +
            "LeveransOrt = '" + leveransOrt + "', " +
            "LeveransLand = '" + leveransLand + "', " +
            "FakturaAdress = '" + fakturaAdress + "', " +
            "FakturaPostnummer = '" + fakturaPostNr + "', " +
            "FakturaOrt = '" + fakturaOrt + "', " +
            "FakturaLand = '" + fakturaLand + "' " +
            "WHERE KundID = " + kundID;

        idb.update(updateQuery);
        JOptionPane.showMessageDialog(this, "Kundinformation har uppdaterats.");
        setEditable(false);
        BtnRedigera.setEnabled(true);
        BtnSpara.setEnabled(false);
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Ett fel inträffade vid uppdatering: " + ex.getMessage());
    }
    }//GEN-LAST:event_BtnSparaActionPerformed

    private void BtnRedigeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRedigeraActionPerformed
        setEditable(true); // Gör textfälten redigerbara
        BtnSpara.setEnabled(true); // Aktivera Spara-knappen
        BtnRedigera.setEnabled(false); // Deaktivera Redigera-knappen
    }//GEN-LAST:event_BtnRedigeraActionPerformed

    private void BtnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTaBortActionPerformed
    try {
        int svar = JOptionPane.showConfirmDialog(this, "Vill du verkligen ta bort kundens uppgifter (förutom KundID)?", "Bekräfta", JOptionPane.YES_NO_OPTION);

        if (svar == JOptionPane.YES_OPTION) {
            String rensaKundUppgifter = "UPDATE Kund SET " +
                "Fornamn = NULL, " +
                "Efternamn = NULL, " +
                "Epost = NULL, " +
                "Telefonnummer = NULL, " +
                "LeveransAdress = NULL, " +
                "LeveransPostnummer = NULL, " +
                "LeveransOrt = NULL, " +
                "LeveransLand = NULL, " +
                "FakturaAdress = NULL, " +
                "FakturaPostnummer = NULL, " +
                "FakturaOrt = NULL, " +
                "FakturaLand = NULL " +
                "WHERE KundID = " + kundID + ";";

            idb.update(rensaKundUppgifter);

            JOptionPane.showMessageDialog(this, "Kundens uppgifter har rensats. KundID finns kvar.");
            
            // Öppna AllaKunder och stäng nuvarande fönster
            new AllaKunder(idb, inloggadAnvandare).setVisible(true);
            this.dispose();
        }
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Ett fel inträffade vid rensning: " + ex.getMessage());
    }
    }//GEN-LAST:event_BtnTaBortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpecifikKund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpecifikKund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpecifikKund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpecifikKund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //new SpecifikKund().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRedigera;
    private javax.swing.JButton BtnSpara;
    private javax.swing.JButton BtnTaBort;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFakturaPostNr;
    private javax.swing.JLabel lblFakturaadress;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblLeveransPostNr;
    private javax.swing.JLabel lblLeveransadress;
    private javax.swing.JLabel lblTelefonnummer;
    private javax.swing.JTextField txtEfternamn;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtFakturaAdress;
    private javax.swing.JTextField txtFakturaLand;
    private javax.swing.JTextField txtFakturaOrt;
    private javax.swing.JTextField txtFakturaPostNr;
    private javax.swing.JTextField txtFornamn;
    private javax.swing.JTextField txtKundID;
    private javax.swing.JTextField txtLeveransAdress;
    private javax.swing.JTextField txtLeveransLand;
    private javax.swing.JTextField txtLeveransOrt;
    private javax.swing.JTextField txtLeveransPostNr;
    private javax.swing.JTextField txtTelefonnummer;
    // End of variables declaration//GEN-END:variables
}
